### ISSUE TITLE
[BUG] NullReferenceException: Object reference not set to an instance of an object   at MolecularLib.AutoAssign.AutoAssignController.Start

### ISSUE THREAD

**Issue by XeonG** [Heymity/MolecularLibCore#4]
In a build.. .actually not using anything that I know of in this library yet (with this project).. but got this:

NullReferenceException: Object reference not set to an instance of an object
  at MolecularLib.AutoAssign.AutoAssignController.Start () [0x00002] in C:\Projects\Unity\test\Assets\Plugins\MolecularLibCore\HandsomeDinosaur\MolecularLib\Core\AutoAssign\AutoAssignController.cs:44 

(Filename: C:/Projects/Unity/test/Assets/Plugins/MolecularLibCore/HandsomeDinosaur/MolecularLib/Core/AutoAssign/AutoAssignController.cs Line: 44)

**Comment by Heymity** [comment]
Thanks for the report, I will look into it!

**Comment by Heymity** [comment]
I could not reproduce your bug, still, I made some changes that should prevent this bug from happening. This was probably due to this method being called at the same time that the TypeLibrary is loaded, this was changed and a check was added to prevent the collection accessed in the TypeLibrary class from being null. 

All the changes are in the AutoAssignBuildBug branch, and since I could not reproduce the bug, if you could test it and check whether the bug was fixed or not I would thank you.

In any case, this update will probably be pushed into the asset store by Friday, or before, if I receive confirmation that the bug is fixed.

Thanks for the report!
